apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URI
              value: pg-service
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: LoadBalancer  # Makes the backend accessible from the internet
  selector:
    app: backend
  ports:
    - port: 80         # Exposed externally
      targetPort: 5000 # Inside container
