apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/frontend-p:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # <== changed from NodePort to LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
